version: '3'
services:
  mysql:
    container_name: mysql3790
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bsbs
    volumes:
      - E:/IoT/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql

  mqtt:
    container_name: mqtt3790
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - C:\Program Files\mosquitto:\mosquitto/config/mosquitto.conf

  python:
    build:
      context: E:\IoT\backend
    ports:
      - "3790:3790"
    environment:
      - DB_HOST=mysql3790
      - MQTT_HOST=mqtt3790
    depends_on:
      - mysql
      - mqtt

  react:
    image: nginx:latest
    volumes:
      - E:\IoT\react\build:/usr/share/nginx/html  # 将 React build 目录映射到 Nginx 的默认服务目录
    ports:
      - "3002:80"  # 将主机的 3002 端口映射到容器的 80 端口(nginx 默认端口)
    depends_on:
      - python

volumes:
  db-data: