version: '3'
services:
  mysql:
    container_name: mysql3790
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bsbs
    volumes:
      - E:/IoT/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql

  mqtt:
    container_name: mqtt3790
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - E:/IoT/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  python:
    container_name: python3790
    build:
      context: E:\IoT\backend
    ports:
      - "3790:3790"
    environment:
      - DB_HOST=mysql3790
      - MQTT_HOST=mqtt3790
    depends_on:
      - mysql
      - mqtt

  java:
    container_name: java3790
    build:
      context: E:/IoT/client
    ports:
      - "8080:8080"
    environment:
      - MQTT_HOST=tcp://mqtt3790:1883
    depends_on:
      - mysql
      - mqtt

  react:
    container_name: react3790
    image: nginx:latest
    volumes:
      - E:/IoT/react/build:/usr/share/nginx/html
    ports:
      - "3002:80"  # 将主机的 3002 端口映射到容器的 80 端口(nginx 默认端口)
    depends_on:
      - python

volumes:
  db-data: